image: debian:latest

pipelines:
  default:

    - step:
        name: gcc-external-dep-mpi
        image: mparno/muq-build:latest
        script:

          # Build muq
          - cd $BITBUCKET_CLONE_DIR
          - cd build
          - cmake -DMUQ_USE_GTEST=ON -DMUQ_USE_MPI=ON -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc -DMUQ_USE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/home/muq-user/install ..
          - make
          - make examples
          - make install
          - ./RunAllTests
          - mpirun -np 2 ./RunAllParallelTests

  tags:
    'v*.*.*':
      # - step:
      #       name: docker-muq-build
      #       script:
      #         - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      #         - cd $BITBUCKET_CLONE_DIR/SupportScripts/docker/muq-build
      #         - docker build --build-arg tag=$BITBUCKET_TAG -t mparno/muq-build:$BITBUCKET_TAG .
      #         - docker push mparno/muq-build:$BITBUCKET_TAG
      #       services:
      #         - docker
      # - step:
      #       name: docker-muq
      #       size: 2x
      #       script:
      #         - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      #         - cd $BITBUCKET_CLONE_DIR/SupportScripts/docker/muq
      #         - docker build --build-arg tag=$BITBUCKET_TAG -t mparno/muq:$BITBUCKET_TAG .
      #         - docker push mparno/muq:$BITBUCKET_TAG
      #       services:
      #         - docker
      # - step:
      #       name: docker-muq-jupyter
      #       script:
      #         - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      #         - cd $BITBUCKET_CLONE_DIR/SupportScripts/docker/muq-jupyter
      #         - docker build --build-arg tag=$BITBUCKET_TAG -t mparno/muq-jupyter:$BITBUCKET_TAG .
      #         - docker push mparno/muq-jupyter:$BITBUCKET_TAG
      #       services:
      #         - docker
      # - step:
      #       name: docker-muq-hippylib
      #       size: 2x
      #       script:
      #         - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      #         - cd $BITBUCKET_CLONE_DIR/SupportScripts/docker/muq-hippylib
      #         - docker build --build-arg tag=$BITBUCKET_TAG -t mparno/muq-hippylib:$BITBUCKET_TAG .
      #         - docker push mparno/muq-hippylib:$BITBUCKET_TAG
      #       services:
      #         - docker
      - step:
            name: documentation
            image: mparno/muq-build
            script:
              - apt-get update
              - apt-get install -y doxygen
              - cd $BITBUCKET_CLONE_DIR/build
              - cmake -DMUQ_USE_GTEST=ON -DMUQ_USE_MPI=ON -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc -DMUQ_USE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/home/muq-user/install ..
              - make doc
              - cd ~
              - git clone https://$BITBUCKET_USER:$BITBUCKET_PASSWORD@bitbucket.org/mituq/mituq.bitbucket.io.git
              - cd mituq.bitbucket.io
              - if [ -d "$BITBUCKET_TAG" ]; then rm -Rf $BITBUCKET_TAG; fi
              - mv $BITBUCKET_CLONE_DIR/build/doxygen_output/html $BITBUCKET_TAG
              - if [[ "$BITBUCKET_TAG" =~ ^v[0-9].[0-9]+.[0-9]+$ ]]; then echo "<meta http-equiv=\"refresh\" content=\"0; url=https://mituq.bitbucket.io/$BITBUCKET_TAG/index.html\">" > index.html; fi
              - git add $BITBUCKET_TAG
              - if [[ "$BITBUCKET_TAG" =~ ^v[0-9].[0-9]+.[0-9]+$ ]]; then git add index.html; fi
              - git commit -m "Added documentation for $BITBUCKET_TAG"
              - git push $BITBUCKET_USER:$BITBUCKET_PASSWORD@bitbucket.org/mituq/mituq.bitbucket.io.git --all

  custom:
    weekly-build:
      - parallel:

        - step:
              name: clang-external-dep
              image: mparno/muq-build:latest
              script:

                # Build muq
                - cd $BITBUCKET_CLONE_DIR
                - cd build
                - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DMUQ_USE_GTEST=ON -DMUQ_USE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/home/muq-user/install ..
                - make
                - make examples
                - make install
                - ./RunAllTests

        - step:
            name: clang-internal-dep-mpi
            script:
              - apt-get update
              - apt-get install -y cmake openmpi-bin libopenmpi-dev libgtest-dev clang python-dev


              # Build gtest (have to, since libgtest-dev only includes sources, no binaries available currently...)
              - cd /usr/src/gtest
              - cmake CMakeLists.txt
              - make
              - cp *.a /usr/lib

              - export OMPI_CXX=clang++ # Need this to make sure openmpi actually uses clang

              # Build muq
              - cd $BITBUCKET_CLONE_DIR
              - cd build
              - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DMUQ_USE_GTEST=ON -DMUQ_USE_MPI=ON -DMUQ_USE_PYTHON=ON ..
              - make
              - make examples
              - make install
              - ./RunAllTests
              - mpirun --allow-run-as-root -np 2 ./RunAllParallelTests

        - step:
            name: gcc-external-dep-mpi
            image: mparno/muq-build:latest
            script:

              # Build muq
              - cd $BITBUCKET_CLONE_DIR
              - cd build
              - cmake -DMUQ_USE_GTEST=ON -DMUQ_USE_MPI=ON -DMUQ_USE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/home/muq-user/install ..
              - make
              - make examples
              - make install
              - ./RunAllTests
              - mpirun -np 2 ./RunAllParallelTests

        - step:
              name: ubuntu-LTS
              image: ubuntu:latest
              script:
                - apt-get update
                - DEBIAN_FRONTEND="noninteractive" apt-get install -y cmake libgtest-dev clang libhdf5-dev libeigen3-dev libboost-all-dev libnlopt-dev libsundials-dev python-dev pybind11-dev


                # Build gtest (have to, since libgtest-dev only includes sources, no binaries available currently...)
                - cd /usr/src/gtest
                - cmake CMakeLists.txt
                - make
                - cp lib/*.a /usr/lib


                # Build muq
                - cd $BITBUCKET_CLONE_DIR
                - cd build
                - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DMUQ_USE_GTEST=ON -DMUQ_USE_PYTHON=ON ..
                - make
                - make examples
                - make install
                - ./RunAllTests

        - step:
              name: ubuntu-latest-release
              image: ubuntu:rolling
              script:
                - apt-get update
                - DEBIAN_FRONTEND="noninteractive" apt-get install -y cmake libgtest-dev clang libhdf5-dev libeigen3-dev libboost-all-dev libnlopt-dev libsundials-dev python-dev pybind11-dev


                # Build gtest (have to, since libgtest-dev only includes sources, no binaries available currently...)
                - cd /usr/src/gtest
                - cmake CMakeLists.txt
                - make
                - cp lib/*.a /usr/lib


                # Build muq
                - cd $BITBUCKET_CLONE_DIR
                - cd build
                - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DMUQ_USE_GTEST=ON -DMUQ_USE_PYTHON=ON ..
                - make
                - make examples
                - make install
                - ./RunAllTests

        - step:
              name: install-instructions
              image: ubuntu:latest
              script:
                - apt update
                - DEBIAN_FRONTEND="noninteractive" apt install -y sudo tzdata
                - cd $BITBUCKET_CLONE_DIR
                - cd SupportScripts
                - bash install-instructions.sh
