name: Dimension Independent MCMC with DILI
language: python
code_files: EllipticInference.py
doc_level: Fair # Should be "None", "Fair", "Good", or "Excellent"
run_command: python EllipticInference.py
