- example:
    file: GaussianGammaSampling.cpp
    tag: MCMC
    title: Basic Metropolis-in-Gibbs Sampling
    description: Metropolis-in-Gibbs sampling of a simple hierarchical Bayesian model with Gaussian-Inverse target density.
