- example:
    file: GaussianProcess_CO2.cpp
    tag: Gaussian Process
    title: Mauna Loa CO2
    description: Regression of CO2 observations with a statespace representation of a Gaussian process.
