- example:
    file: GaussianGammaSampling.ipynb
    tag: MCMC
    title: Gaussian Gamma Sampling
    description: Define a joint Gaussian-Inverse Gamma target density using MUQ's model graph, then sampling from it via MCMC.
