package:
  name: muq2
  version: '0.2.0'

source:
  git_url: https://bitbucket.org/mituq/muq2.git
  git_tag: conda-build

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pybind11
    - boost
    - eigen
    - h5py
    - lapack
    - sundials ==2.6.2
    - nanoflann
    - nlopt
    - mkl
  run:
    - python
    - boost
    - eigen
    - h5py
    - lapack
    - sundials ==2.6.2
    - nanoflann
    - nlopt
    - mkl

test:
  imports:
    - muq.Approximation
    - muq.Modeling
    - muq.Optimization
    - muq.SamplingAlgorithms
    - muq.Utilities

about:
  home: http://muq.mit.edu
  license: BSD
  summary: 'MIT Uncertainty Quantification Library (MUQ) is a collection of tools for constructing models and a collection of uncertainty quantification (UQ)–focused algorithms for working on those models.'
